//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NET_StoreManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputDetail
    {
        public int Id { get; set; }
        public Nullable<int> InputId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Input Input { get; set; }
        public virtual Product Product { get; set; }
    }
}
